version: "3"
services:
  server:
    build:
      context: ../../ 
      dockerfile: docker/dev/Dockerfile
    container_name: phone-gen-server
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ../../:/app
